### ISSUE TITLE
bug: Args not inherited in class docstrings

### ISSUE THREAD

**Issue by cnellington** [AntoineD/docstring-inheritance#19]
### Description of the bug
Google style supports `__init__` args in class docstrings `Args:` (e.g. class ExampleError in [Napoleon](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)), but currently only attributes are inherited. Same with numpy style `Parameters`. Rendering args in class docstring also breaks with mkdocstrings when attempting to inherit args.

### To Reproduce
```
from docstring_inheritance import GoogleDocstringInheritanceMeta


class Parent(metaclass=GoogleDocstringInheritanceMeta):
    """Parent class

    Attributes:
        w: Description for w
        x: Description for x
        y: Description for y
    
    Args:
        a: arg
    """
    def __init__(self, a):
        self.a = a


class Child(Parent):
    """Child class

    Attributes:
        z: Description for z
        y: Overridden description for y

    Args:
        a: overwritten arg
    """
    def __init__(self, a):
        self.a = a


print(Child.__doc__)
```

### Output

```python
Child class

Attributes:
    w: Description for w
    x: Description for x
    y: Overridden description for y
    z: Description for z
```
Note the missing `Args: ` section as well.

</details>

### Expected output

```
Child class

Attributes:
    w: Description for w
    x: Description for x
    y: Overridden description for y
    z: Description for z

Args:
    a: overwritten arg
```
